"use client"
import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ImageUploader, type UploadedImage } from '@/components/admin/image-uploader'
import { toast } from 'sonner'
import { ArrowDown, ArrowUp, Eye, Plus, Save, Trash2 } from 'lucide-react'
import type { SiteBlock, SiteConfig } from '@/lib/site-config'

const blockTypes: Array<SiteBlock['type']> = ['hero','richtext','image-text','products','categories','features','stats','gallery','testimonials','cta','contact','spacer']
const blankBlock=(type:SiteBlock['type'],order:number):SiteBlock=>({id:`block-${crypto.randomUUID()}`,type,enabled:true,title:'',subtitle:'',data:{},order})

export function SiteDesigner(){
 const [config,setConfig]=useState<SiteConfig|null>(null); const [page,setPage]=useState('home'); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true)
 useEffect(()=>{fetch('/api/site-config',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.success)setConfig(d.data)}).finally(()=>setLoading(false))},[])
 const blocks=useMemo(()=>config?.pages?.[page]?.blocks??[],[config,page])
 function update(patch:Partial<SiteConfig>){setConfig(c=>c?{...c,...patch}:c)}
 function updatePage(patch: any) {
  setConfig(c => {
    if (!c) return c

    const currentPage = c.pages?.[page] ?? {
      slug: page,
      title: page,
      published: true,
      blocks: [],
    }

    return {
      ...c,
      pages: {
        ...c.pages,
        [page]: {
          ...currentPage,
          ...patch,
        },
      },
    }
  })
}
 function updateBlock(id:string,patch:Partial<SiteBlock>){updatePage({blocks:blocks.map(b=>b.id===id?{...b,...patch}:b)})}
 function addBlock(type:SiteBlock['type']){updatePage({blocks:[...blocks,blankBlock(type,blocks.length)]})}
 function move(id:string,dir:number){const arr=[...blocks].sort((a,b)=>a.order-b.order);const i=arr.findIndex(x=>x.id===id);const j=i+dir;if(i<0||j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];updatePage({blocks:arr.map((b,n)=>({...b,order:n}))})}
 function remove(id:string){updatePage({blocks:blocks.filter(b=>b.id!==id).map((b,i)=>({...b,order:i}))})}
 async function save(){if(!config)return;setSaving(true);try{const r=await fetch('/api/site-config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'ذخیره ناموفق بود');toast.success('طراحی سایت ذخیره شد')}catch(e){toast.error(e instanceof Error?e.message:'ذخیره ناموفق بود')}finally{setSaving(false)}}
 if(loading||!config)return <div className="h-96 rounded-xl shimmer"/>
 return <div className="space-y-6">
  <div className="flex items-center justify-between gap-3"><div><h2 className="text-2xl font-black">طراحی سایت بدون کدنویسی</h2><p className="text-sm text-muted-foreground mt-1">برند، رنگ، منو، صفحه‌ها، بخش‌ها و تصاویر را از همین پنل مدیریت کنید.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>window.open('/','_blank')}><Eye className="w-4 h-4 ml-2"/>پیش‌نمایش سایت</Button><Button onClick={save} disabled={saving}><Save className="w-4 h-4 ml-2"/>{saving?'در حال ذخیره...':'ذخیره تغییرات'}</Button></div></div>
  <div className="grid lg:grid-cols-[280px_1fr] gap-5">
   <Card className="p-4 space-y-2 h-fit"><div className="font-bold mb-2">بخش‌های قابل تنظیم</div>{['branding','theme','navigation','home','about','contact','footer','seo'].map(id=><button key={id} onClick={()=>setPage(id)} className={`w-full text-right rounded-lg px-3 py-2 text-sm ${page===id?'bg-primary text-primary-foreground':'hover:bg-accent'}`}>{({branding:'برند و اطلاعات کسب‌وکار',theme:'رنگ و ظاهر',navigation:'منوی سایت',home:'صفحه اصلی',about:'صفحه درباره ما',contact:'صفحه تماس',footer:'فوتر',seo:'SEO و شبکه‌های اجتماعی'} as any)[id]}</button>)}</Card>
   <div className="space-y-5">
    {page==='branding'&&<Branding config={config} setConfig={setConfig}/>} 
    {page==='theme'&&<Theme config={config} setConfig={setConfig}/>} 
    {page==='navigation'&&<NavigationEditor config={config} setConfig={setConfig}/>} 
    {page==='footer'&&<FooterEditor config={config} setConfig={setConfig}/>} 
    {page==='seo'&&<SeoEditor config={config} setConfig={setConfig}/>} 
    {['home','about','contact'].includes(page)&&<><Card className="p-5"><Label>عنوان صفحه</Label><Input value={config.pages?.[page]?.title||''} onChange={e=>updatePage({title:e.target.value})} className="mt-2"/><div className="mt-4 flex items-center justify-between"><div><Label>انتشار صفحه</Label><p className="text-xs text-muted-foreground">صفحه فقط وقتی Published باشد در سایت نمایش داده می‌شود.</p></div><Switch checked={config.pages?.[page]?.published!==false} onCheckedChange={v=>updatePage({published:v})}/></div></Card><BlockEditor blocks={blocks} updateBlock={updateBlock} addBlock={addBlock} move={move} remove={remove}/></>}
   </div>
  </div>
 </div>
}

function Branding({config,setConfig}:{config:SiteConfig,setConfig:Dispatch<SetStateAction<SiteConfig|null>>}){const b=config.brand;const set=(k:string,v:string)=>setConfig(c=>c?{...c,brand:{...c.brand,[k]:v}}:c);const uploaded:UploadedImage[]=b.logoUrl?[{id:b.logoMediaId||'logo',url:b.logoUrl,originalName:'logo',mimeType:'image/*',size:0}]:[];return <Card className="p-5 space-y-5"><h3 className="font-bold text-lg">اطلاعات واقعی کسب‌وکار</h3><div className="grid md:grid-cols-2 gap-4">{[['nameFa','نام کسب‌وکار فارسی'],['nameEn','نام کسب‌وکار انگلیسی'],['taglineFa','شعار فارسی'],['taglineEn','شعار انگلیسی'],['phone','تلفن'],['email','ایمیل'],['whatsapp','واتساپ'],['city','شهر'],['country','کشور'],['instagram','اینستاگرام'],['telegram','تلگرام'],['youtube','یوتیوب'],['linkedin','لینکدین'],['mapUrl','لینک نقشه']].map(([k,l])=><div key={k}><Label>{l}</Label><Input value={(b as any)[k]||''} onChange={e=>set(k,e.target.value)} className="mt-2" dir={['email','phone','whatsapp','instagram','telegram','youtube','linkedin','mapUrl'].includes(k)?'ltr':'rtl'}/></div>)}</div><div><Label>آدرس</Label><Textarea value={b.address||''} onChange={e=>set('address',e.target.value)} className="mt-2" rows={3}/></div><div><Label>ساعات کاری</Label><Input value={b.workingHours||''} onChange={e=>set('workingHours',e.target.value)} className="mt-2"/></div><div><Label>لوگو</Label><div className="mt-2"><ImageUploader value={uploaded} multiple={false} onChange={items=>setConfig(c=>c?{...c,brand:{...c.brand,logoUrl:items[0]?.url||'',logoMediaId:items[0]?.id||''}}:c)}/></div></div></Card>}
function Theme({config,setConfig}:{config:SiteConfig,setConfig:Dispatch<SetStateAction<SiteConfig|null>>}){const t=config.theme;const set=(k:string,v:string)=>setConfig(c=>c?{...c,theme:{...c.theme,[k]:v}}:c);return <Card className="p-5"><h3 className="font-bold text-lg mb-5">هویت بصری و ظاهر</h3><div className="grid md:grid-cols-2 gap-5">{[['primary','رنگ اصلی'],['secondary','رنگ تیره'],['accent','رنگ تأکیدی'],['background','پس‌زمینه'],['foreground','رنگ متن'],['muted','پس‌زمینه فرعی'],['radius','گردی گوشه‌ها']].map(([k,l])=><div key={k}><Label>{l}</Label><Input value={(t as any)[k]||''} onChange={e=>set(k,e.target.value)} className="mt-2" dir="ltr"/></div>)}<div><Label>فونت</Label><Input value={t.font||''} onChange={e=>set('font',e.target.value)} className="mt-2" dir="ltr"/></div><div><Label>نوع کارت</Label><Select value={t.cardStyle} onValueChange={v=>set('cardStyle',v)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="soft">نرم</SelectItem><SelectItem value="flat">ساده</SelectItem><SelectItem value="bordered">کادربندی</SelectItem></SelectContent></Select></div><div><Label>نوع دکمه</Label><Select value={t.buttonStyle} onValueChange={v=>set('buttonStyle',v)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="rounded">گرد</SelectItem><SelectItem value="pill">کپسولی</SelectItem><SelectItem value="square">مربع</SelectItem></SelectContent></Select></div></div></Card>}
function NavigationEditor({config,setConfig}:{config:SiteConfig,setConfig:Dispatch<SetStateAction<SiteConfig|null>>}){const items=[...config.nav].sort((a,b)=>a.order-b.order);return <Card className="p-5"><div className="flex justify-between mb-5"><h3 className="font-bold text-lg">منوی سایت</h3><Button onClick={()=>setConfig(c=>c?{...c,nav:[...c.nav,{label:'',href:'',enabled:true,order:c.nav.length}]}:c)}><Plus className="w-4 h-4 ml-2"/>افزودن آیتم</Button></div><div className="space-y-3">{items.map((it,i)=><div key={`${it.href}-${i}`} className="grid md:grid-cols-[1fr_1fr_auto_auto] gap-2 items-end border rounded-xl p-3"><div><Label>عنوان</Label><Input value={it.label} onChange={e=>setConfig(c=>c?{...c,nav:c.nav.map((x,n)=>n===i?{...x,label:e.target.value}:x)}:c)}/></div><div><Label>مسیر</Label><Input value={it.href} onChange={e=>setConfig(c=>c?{...c,nav:c.nav.map((x,n)=>n===i?{...x,href:e.target.value}:x)}:c)} dir="ltr"/></div><div className="flex items-center gap-2"><Switch checked={it.enabled} onCheckedChange={v=>setConfig(c=>c?{...c,nav:c.nav.map((x,n)=>n===i?{...x,enabled:v}:x)}:c)}/><span className="text-xs">نمایش</span></div><Button variant="ghost" size="icon" onClick={()=>setConfig(c=>c?{...c,nav:c.nav.filter((_,n)=>n!==i).map((x,n)=>({...x,order:n}))}:c)}><Trash2 className="w-4 h-4"/></Button></div>)}</div></Card>}
function FooterEditor({config,setConfig}:{config:SiteConfig,setConfig:Dispatch<SetStateAction<SiteConfig|null>>}){const f=config.footer;return <Card className="p-5 space-y-4"><Label>متن فوتر</Label><Textarea value={f.text||''} onChange={e=>setConfig(c=>c?{...c,footer:{...f,text:e.target.value}}:c)} rows={3}/><div className="text-sm text-muted-foreground">لینک‌های فوتر از بخش «منوی سایت» و تنظیمات کسب‌وکار استفاده می‌کنند.</div></Card>}
function SeoEditor({config,setConfig}:{config:SiteConfig,setConfig:Dispatch<SetStateAction<SiteConfig|null>>}){const s=config.seo;const og=s.ogImage?[{id:'og',url:s.ogImage,originalName:'og',mimeType:'image/*',size:0}]:[];return <Card className="p-5 space-y-4"><h3 className="font-bold text-lg">SEO</h3>{[['title','عنوان سراسری'],['description','توضیحات متا'],['keywords','کلمات کلیدی'],['canonical','Canonical URL'],['twitterHandle','Twitter/X Handle']].map(([k,l])=><div key={k}><Label>{l}</Label><Input value={(s as any)[k]||''} onChange={e=>setConfig(c=>c?{...c,seo:{...c.seo,[k]:e.target.value}}:c)} className="mt-2" dir={k==='description'?'rtl':'ltr'}/></div>)}<div><Label>تصویر Open Graph</Label><ImageUploader value={og} multiple={false} onChange={items=>setConfig(c=>c?{...c,seo:{...c.seo,ogImage:items[0]?.url||''}}:c)}/></div></Card>}
function BlockEditor({blocks,updateBlock,addBlock,move,remove}:{blocks:SiteBlock[],updateBlock:(id:string,p:Partial<SiteBlock>)=>void,addBlock:(t:SiteBlock['type'])=>void,move:(id:string,d:number)=>void,remove:(id:string)=>void}){return <div className="space-y-4"><div className="flex flex-wrap gap-2">{blockTypes.map(t=><Button key={t} variant="outline" size="sm" onClick={()=>addBlock(t)}><Plus className="w-3 h-3 ml-1"/>{t}</Button>)}</div>{blocks.map((b,i)=><Card key={b.id} className="p-4 space-y-4"><div className="flex items-center justify-between"><div className="font-bold">{i+1}. {b.type}</div><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={()=>move(b.id,-1)}><ArrowUp className="w-4 h-4"/></Button><Button variant="ghost" size="icon" onClick={()=>move(b.id,1)}><ArrowDown className="w-4 h-4"/></Button><Button variant="ghost" size="icon" onClick={()=>remove(b.id)}><Trash2 className="w-4 h-4"/></Button></div></div><div className="flex items-center justify-between"><span className="text-sm">فعال</span><Switch checked={b.enabled} onCheckedChange={v=>updateBlock(b.id,{enabled:v})}/></div><div className="grid md:grid-cols-2 gap-4"><div><Label>عنوان</Label><Input value={b.title||''} onChange={e=>updateBlock(b.id,{title:e.target.value})}/></div><div><Label>زیرعنوان</Label><Input value={b.subtitle||''} onChange={e=>updateBlock(b.id,{subtitle:e.target.value})}/></div></div><BlockFields block={b} update={p=>updateBlock(b.id,p)}/></Card>)}</div>}
function BlockFields({block,update}:{block:SiteBlock,update:(p:Partial<SiteBlock>)=>void}){const d=block.data||{};const setD=(k:string,v:any)=>update({data:{...d,[k]:v}});if(block.type==='hero')return <div className="space-y-3"><Label>متن اصلی</Label><Textarea value={d.body as string||''} onChange={e=>setD('body',e.target.value)} rows={4}/><Label>تصویر پس‌زمینه</Label><ImageUploader value={block.imageUrl?[{id:String(d.imageMediaId||'hero'),url:block.imageUrl,originalName:'hero',mimeType:'image/*',size:0}]:[]} multiple={false} onChange={items=>update({imageUrl:items[0]?.url||'',data:{...d,imageMediaId:items[0]?.id||''}})}/></div>;if(block.type==='image-text')return <div className="space-y-3"><Label>متن</Label><Textarea value={d.body as string||''} onChange={e=>setD('body',e.target.value)} rows={6}/><Label>تصویر</Label><ImageUploader value={block.imageUrl?[{id:String(d.imageMediaId||'image-text'),url:block.imageUrl,originalName:'image-text',mimeType:'image/*',size:0}]:[]} multiple={false} onChange={items=>update({imageUrl:items[0]?.url||'',data:{...d,imageMediaId:items[0]?.id||''}})}/></div>;if(block.type==='products')return <div className="grid md:grid-cols-2 gap-4"><div><Label>منبع محصولات</Label><Select value={String(d.source||'featured')} onValueChange={v=>setD('source',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="featured">ویژه</SelectItem><SelectItem value="newest">جدیدترین</SelectItem><SelectItem value="bestseller">پرفروش</SelectItem><SelectItem value="export">صادراتی</SelectItem></SelectContent></Select></div><div className="flex items-center gap-2"><Switch checked={Boolean(d.alt)} onCheckedChange={v=>setD('alt',v)}/><span>پس‌زمینه متفاوت</span></div></div>;if(['richtext','image-text','cta'].includes(block.type))return <div><Label>متن</Label><Textarea value={d.body as string||''} onChange={e=>setD('body',e.target.value)} rows={6}/></div>;if(['features','stats','testimonials'].includes(block.type))return <div><Label>آیتم‌ها (JSON)</Label><Textarea value={JSON.stringify(d.items||[],null,2)} onChange={e=>{try{setD('items',JSON.parse(e.target.value))}catch{}}} rows={8} dir="ltr"/><p className="text-xs text-muted-foreground mt-1">این بخش تنها محتوای ساختاریافته است؛ HTML/Script اجرا نمی‌شود.</p></div>;if(block.type==='gallery')return <div><Label>تصاویر گالری</Label><ImageUploader value={Array.isArray(d.images)?(d.images as string[]).map((url,i)=>({id:String((d.imageMediaIds as string[]|undefined)?.[i]||i),url,originalName:`gallery-${i+1}`,mimeType:'image/*',size:0})):[]} onChange={items=>setD('images',items.map(x=>x.url))}/></div>;return <div className="text-sm text-muted-foreground">این بلوک تنظیمات اضافی ندارد.</div>}
